### PR TITLE
fix(providers): ensure prepared statements for pool clients

### LINKED ISSUE #3998: [BUG] Intermittent sql failures during high load
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [x] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

When I run the postgres provider, I get these intermittent errors of:
`Error executing get query: QueryError::Unexpected(\"failed to perform query: db error: ERROR: prepared statement \\\"s1035\\\" does not exist\")"`

### Steps to reproduce

Run postgres provider in an app

Run frequent prepare and execute calls to the postgres provider

### Expected behavior

Far less to no intermittent errors

### Environment

MacOS and Linux
using wasmcloud 1.5.0

### Screenshots / Logs / Additional context

_No response_

### PR DESCRIPTION
**Pull request by vados-cosmonic**
This commit fixes an issue with the postgres provider in which it did not ensure that a single client from the pool had a statement prepared for it.

Statements are `prepare`d for single clients, but `deadpool_postgres` does not support preparing for a pool, so we must use the statement cache on a given client pulled out of the pool to ensure the statement we're about to use has been `prepare`d.

Resolves #3998

### CODE REVIEW

**Comment by vados-cosmonic** [comment]
Hey @LUK3ARK would you mind trying this out and confirming it fixes your issue? You can use [my built provider](https://github.com/vados-cosmonic/wasmCloud/pkgs/container/sqldb-postgres/374298181?tag=0.8.0-stmt-fix) if you're on Linux.

File: crates/provider-sqldb-postgres/src/lib.rs [hunk 1]
```diff
@@ -246,7 +279,9 @@ impl Provider for PostgresProvider {
     async fn delete_link_as_target(&self, info: impl LinkDeleteInfo) -> anyhow::Result<()> {
         let component_id = info.get_source_id();
         let mut prepared_statements = self.prepared_statements.write().await;
-        prepared_statements.retain(|_stmt_token, (_conn, src_id)| component_id != *src_id);
+        // TODO: this is wrong? source id != connection token??
```
Comment (thomastaylor312) [inline crates/provider-sqldb-postgres/src/lib.rs:282]: I think this is right? Retaining all things where the component ID isn't the source ID. Or did I misunderstand?

**Review by thomastaylor312 — COMMENTED** [review]
Good to go once we can confirm this solves @LUK3ARK's issue

**Review by thomastaylor312 — APPROVED** [review]

File: crates/provider-sqldb-postgres/src/lib.rs (hunk 1 above)
Comment (vados-cosmonic) [reply crates/provider-sqldb-postgres/src/lib.rs]: Yeah it just wasn't clear -- I was using a custom token at one point, but it's actually source ID -- updated now.

**Comment by LUK3ARK** [comment]
Haven't tested under **heavy** load like the initial situation, but this works for me! I guess this is good and an improvement and still works so best to merge and if I still have issues I will just PR changes on top.

The main issue was the fact that statements would sometimes just not exist consistently this seems to fix that
