### PR TITLE
fix(washboard-ui): provider status is in incorrect state

### LINKED ISSUE #2627: [BUG] washboard provider view shows "pending" perpetually
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [X] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

The wasmCloud dashboard always shows that my provider is "Pending", even when the real state is "Running"

### Steps to reproduce

1. Run wash new component to generate a hello-world project
2. run wash up -d to launch wasmCloud
3. cd component && wash build
4. wash app deploy ./wadm.yaml
5. wash ui
6. visit localhost:3030
7. see Pending

### Expected behavior

I expect for the provider health to automatically 

### Environment

- OS: [e.g. Linux, MacOS]
- Shell [e.g. bash, zsh, powershell]
- wasmcloud Version [e.g. 0.81.0]

### Screenshots / Logs / Additional context

image

However, in wadm_state:
```
➜ nats kv get wadm_state provider_default --raw |jq
{
  "test-arbx_graph": {
    "id": "test-arbx_graph",
    "name": "Custom Provider",
    "issuer": "ABJ6WQ5FBGXECIJBBGA7BG73IKE7ITD2DRAURV5WB5ZUTYTNOOAYGPIG",
    "reference": "file:///Users/brooks/tmp/luk3/footest/fooprovider/build/wasmcloud-provider-custom-template.par.gz",
    "hosts": {
      "NBFN4TRTQ5Q6UANE5R2KAVHCXOIA464MWBCIROGIASV2DRWIBLU3VE5J": "Running"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by markkovari**
## Feature or Problem

As the related issue states, the healthiness of the providers never turn to `Running` although the bucket says otherwise. 

Tested it manually with multiple providers and hosts.
Everything looks good for now, but we might consider test it on multiple levels based on the estimated effort.

## Related Issues

Should fix #2627 .

## Consumer Impact

Should fix the falsy health indicator for providers.

### Manual Verification

1. Start hosts 
 - you can do it with ```wash up --multi-local --label zone=us-east-1 -d``` ways
2. Open wash UI
 - ```wash ui``` 
3. Deploy some applications
 - ```wash new component hello --template-name hello-world-rust```
 - ```cd hello```
 - ```wash build && wash deploy wadm.yaml```
4. Monitor the provider entries health indicator
 - wait it to to be Running and green
5. Validate with 
 ```nats kv get wadm_state provider_default --raw | jq```
6. Be amazed.

### CODE REVIEW

File: typescript/packages/lattice-client-core/src/helpers.ts [hunk 1]
```diff
@@ -1,79 +1,95 @@
-import {type QueuedIterator} from 'nats.ws';
-import {connect} from 'nats.ws';
+import {type QueuedIterator} from "nats.ws";
+import {connect} from "nats.ws";
 import {
```
Comment (brooksmtownsend) [inline typescript/packages/lattice-client-core/src/helpers.ts:3]: nit: looks like this is a lot of lint changes (spaces -> tabs, " -> '), should we revert those?

**Review by brooksmtownsend — APPROVED** [review]
All the provider bits LGTM, leaving to @lachieh to give a final approve/merge

File: typescript/packages/lattice-client-core/src/helpers.ts (hunk 1 above)
Comment (markkovari) [reply typescript/packages/lattice-client-core/src/helpers.ts]: You are absolutely right, I used the biome linter/formatter and it automatically adjusted things. It looks better now.

File: typescript/apps/washboard-ui/src/app/components/providers-table.tsx [hunk 2]
```diff
@@ -69,21 +75,12 @@ const columns = [
...
-          }
-        },
-        'Running',
-      ) as 'Running' | 'Pending' | 'Failed';
+      const healthSummary = Object.values(info.getValue()).reduce((summary, currentStatus) => {
+        if (summary === 'Failed' || currentStatus === 'Failed') return 'Failed';
+        if (summary === 'Pending' || currentStatus === 'Pending') return 'Pending';
+        if (summary === 'Running' && currentStatus === 'Running') return 'Running';
+        return 'Pending';
+      }, 'Running');
```
Comment (lachieh) [inline typescript/apps/washboard-ui/src/app/components/providers-table.tsx:83]: Much cleaner. Love it!

I've never liked the names of these parameters but won't hold it back as is. If you think of better ones, feel free to change them!

File: typescript/apps/washboard-ui/src/app/components/providers-table.tsx [hunk 3]
```diff
@@ -169,64 +246,7 @@ export function ProvidersTable(): ReactElement {
...
-                ))
-              ) : (
-                <TableRow>
-                  <TableCell colSpan={columns.length} className="h-24 text-center">
-                    No results.
-                  </TableCell>
-                </TableRow>
-              )}
-            </TableBody>
+            <ProviderTableBody {...table} />
```
Comment (lachieh) [inline typescript/apps/washboard-ui/src/app/components/providers-table.tsx:249]: 🎨

File: typescript/packages/lattice-client-core/src/controllers/providers.ts [hunk 4]
```diff
@@ -54,6 +54,21 @@ class ProvidersController extends BaseController {
       JSON.stringify(body),
     );
   }
+
+  /**
+   * Retrieves a list of all providers currently running in the lattice
+   * @returns a list of providers
+   */
+  async list(): Promise<ControlResponse<Record<string, WasmCloudProvider>>> {
```
Comment (lachieh) [inline typescript/packages/lattice-client-core/src/controllers/providers.ts:62]: I know you had a comment about this coming from the bucket. It's definitely not ideal since the bucket data is not a public API, but it's fine until we get some new topics that give us the data we need.

**Review by lachieh — APPROVED** [review]
Approved! Thanks for this @markkovari!

FYI, I turned on auto-merge so this will merge once you mark these comments as resolved.

File: typescript/apps/washboard-ui/src/app/components/providers-table.tsx (hunk 2 above)
Comment (markkovari) [reply typescript/apps/washboard-ui/src/app/components/providers-table.tsx:83]: Well I hesitated to change it to an `Array.prototype.some` and `Array.prototype.every` function with the same logic, but I think it should be good enough. Maybe people who touch it next time will change it.

File: typescript/packages/lattice-client-core/src/controllers/providers.ts (hunk 4 above)
Comment (markkovari) [reply typescript/packages/lattice-client-core/src/controllers/providers.ts:62]: Yeah, you are totally correct, it does not belong here and I we are changing the public API's signature. I've seen that the package is pre 1.x.x so we might get away even removing this. It might worth to review an alternative approach before 1.0.0. But thanks for the heads up, really good to see that you are embracing the SemVer contracting.
