### PR TITLE
fix(wash-cli): add new url to check for washboard releases

### LINKED ISSUE #3428: [BUG] Change of tag pattern for typescript packages breaks wash ui download
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [X] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

In updating the workflows for typescript projects, I added a workflow for releasing washboard. When looking to start the ui with `wash ui`, it expects the tag pattern for to be `washboard-ui-v*` however the pipeline will now be looking for the path to the folder as part of the tag name: `typescript/apps/washboard-ui/v*`

### Steps to reproduce

- Pushing `washboard-ui-*` does not trigger a release
- Pushing `typescript/apps/washboard-ui/v*` prevents `wash ui` from downloading the release

### Expected behavior

We either need to update `wash` to look at the new tag location (probably both patterns) or we need to change the workflow to go back to the expected tag pattern.

### PR DESCRIPTION
**Pull request by lachieh**
Change in the tags for washboard means that washboard is no longer at the same URL. This adds the new URL pattern, and falls back to the old one if it cannot be found.

It might be worth noting that this will need an additional URL when the washboard code moves to its own repo.

Didn't add tests because I wouldn't have a clue where to even start with writing tests in rust but I'm happy to learn if someone wants to give me some direction.

Closes #3428

### CODE REVIEW

File: crates/wash-cli/src/ui/mod.rs [hunk 1]
```diff
@@ -64,33 +64,57 @@ async fn ensure_washboard(version: &str, base_dir: PathBuf) -> Result<PathBuf> {
...
+            Ok(body) => return Ok(body),
+            Err(e) => last_error = Some(e),
+        }
+    }
+
+    Err(last_error.unwrap_or_else(|| anyhow::anyhow!("Failed to find suitable download URL")))
+}
+
+async fn try_download(url: &String) -> Result<bytes::Bytes> {
+    let resp = tls::DEFAULT_REQWEST_CLIENT
```
Comment (markkovari) [inline crates/wash-cli/src/ui/mod.rs:107]: Wow,
 
I do have a really good question here 😄 (someone asked my like an hour ago) could you please use this client instead of `tls::DEFAULT_REQWEST_CLIENT` [this one with magical proxy things in it](https://github.com/wasmCloud/wasmCloud/blob/fc0aea1aa752dcd24d80e011e811b0d0e5a404ac/crates/wash-lib/src/start/github.rs#L95)? Should be a drop-in replacement.


Btw after my pr we can even go ahead and try to fetch the latest "any" version of the washboard too **later**. (this [PR](https://github.com/wasmCloud/wasmCloud/pull/2527) with a bit of modifications)

**Review by vados-cosmonic — APPROVED** [review]
LGTM :rocket:

File: crates/wash-cli/src/ui/mod.rs (hunk 1 above)
Comment (lachieh) [reply crates/wash-cli/src/ui/mod.rs]: updated against main with your changes in, @markkovari!

**Comment by lachieh** [comment]
@brooksmtownsend @vados-cosmonic tagging for visibility next week, this is ready to go and will need to get merged before the next wash release. This is what will allow downloading of washboard@v0.6.0 which includes the fix for #3551

File: crates/wash-cli/src/ui/mod.rs (hunk 1 above)
Comment (markkovari) [reply crates/wash-cli/src/ui/mod.rs]: Thank you

**Comment by markkovari** [comment]
Quick heads up @lachieh the [gh action](https://github.com/wasmCloud/wasmCloud/actions/runs/11984742738/job/33415861333?pr=3652) has been running for like 3.5 - 4 hours, my question regarding this; I think you have hosted runners and the github actions timeout is not the default 1hour, should it make sense to create a timeout not to run the action for more than that? not sure what the longest action is, but might add an upper limit too.

cc @brooksmtownsend 🙈

**Comment by vados-cosmonic** [comment]
Thanks @lachieh ! merging this now :)
