### PR TITLE
fix(wash-lib,wash-cli): do not dowmload wadm on every invocation of wasm up

### LINKED ISSUE #2308: [BUG] wadm binary is fetched on every invocation of wash up
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

It is related to change of `wadm --version` output. recent versions of wadm returns something like `wadm-cli 0.12.0`. Old version returned `wadm 0.10.0`

Check for version string was not updated in wash sources :-(

Actually, I found the bug trying to solve the #2134 digging into source code

### Steps to reproduce

1. check wadm creation time with `ls -l ~/.wash/downloads/wadm`
2. run `wash up`
3. check creation time again, you have a fresh copy

### Expected behavior

Should not download `wadm` for every invocation

### Environment

- OS: All
- Shell: All
- wasmcloud Version 1.0.3

### Screenshots / Logs / Additional context

_No response_

### PR DESCRIPTION
**Pull request by deem0n**
## Feature or Problem

Using regexp to detect wadm version instead of constant prefix. Also added some messages to the user, so he will know wadm version and download URL for wadm if download occurs.

## Related Issues

Resolves #2308 

## Release Information

next

## Consumer Impact

I think all users are affected by the bug. So please include the fix to the next release.

## Testing

run `wash up` and check messages on console.

### Unit Test(s)

nope

### Manual Verification

run `cargo run -- up` in the folder `wasmCloud/crates/wash-cli`

### CODE REVIEW

File: crates/wash-lib/src/start/wadm.rs [hunk 1]
```diff
@@ -74,14 +74,25 @@ where
...
         if let Ok(output) = Command::new(&wadm_bin_path).arg("--version").output().await {
             let stdout = String::from_utf8_lossy(&output.stdout).to_string();
-            if stdout.replace("wadm", "").trim() == version.trim_start_matches('v') {
+            print!("👀 Found wadm version: {}", stdout.trim_end());
+            let re = regex::Regex::new(r"^wadm[^\s]*").unwrap();     
+            if re.replace(&stdout, "").to_string().trim() == version.trim_start_matches('v') {
                 // wadm already exists, return early
+                println!(" Using it.✅");
                 return Ok(wadm_bin_path);
             }
```
Comment (thomastaylor312) [inline crates/wash-lib/src/start/wadm.rs:83]: This should probably have a `print!` newline in an else block in case it doesn't find the right version

**Comment by vados-cosmonic** [comment]
Hey @deem0n would you mind using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) to structure your commit message? Something like:

```
fix(wash-lib,wash-cli): avoid repeated downloads of wadm binary
```

If you want you could also split up the commits to `fix(wash-lib): ...` and `fix(wash-cli): ...` if you want!

File: crates/wash-lib/src/start/wadm.rs [hunk 2]
```diff
@@ -74,14 +74,25 @@ where
         // Check version to see if we need to download new one
         if let Ok(output) = Command::new(&wadm_bin_path).arg("--version").output().await {
             let stdout = String::from_utf8_lossy(&output.stdout).to_string();
-            if stdout.replace("wadm", "").trim() == version.trim_start_matches('v') {
+            print!("👀 Found wadm version: {}", stdout.trim_end());
+            let re = regex::Regex::new(r"^wadm[^\s]*").unwrap();     
+            if re.replace(&stdout, "").to_string().trim() == version.trim_start_matches('v') {
                 // wadm already exists, return early
+                println!(" Using it.✅");
```
Comment (vados-cosmonic) [inline crates/wash-lib/src/start/wadm.rs:81]: It might be nice to make this a bit more explicit -- `"using wadm version [{}]"` or something like that?

And could we keep the emoji location consistent here -- emoji at the front?

**Comment by deem0n** [comment]
Ok, will do today

File: crates/wash-lib/src/start/wadm.rs (hunk 1 above)
Comment (deem0n) [reply crates/wash-lib/src/start/wadm.rs:83]: Refactored!

File: crates/wash-lib/src/start/wadm.rs (hunk 2 above)
Comment (deem0n) [reply crates/wash-lib/src/start/wadm.rs]: Done with emoji, also separated work into 2 commits

Comment (vados-cosmonic) [reply crates/wash-lib/src/start/wadm.rs]: Thanks!

File: crates/wash-lib/src/start/wadm.rs (hunk 1 above)
Comment (deem0n) [reply crates/wash-lib/src/start/wadm.rs:83]: @thomastaylor312: I slightly adjusted the code.

**Review by thomastaylor312 — APPROVED** [review]

**Review by vados-cosmonic — APPROVED** [review]
LGTM :rocket:

Looks like a test was flaky and `cargo fmt` needed to be run.
