### PR TITLE
fix(wash-lib): fix generating from git branch

### LINKED ISSUE #845: [BUG] --branch option in wash new doesn't work
**Describe the bug**
I wanted to `wash new actor` from a branch of a git repo, but wash gives an error when trying to check out the branch:

```bash
wash new actor --git https://github.com/wasmcloud/project-templates --subfolder actor/hello --branch fix/update-deps  
🤷   Project Name : hello3
🔧   Cloning template from repo https://github.com/wasmcloud/project-templates subfolder actor/hello...

git checkout error: error: pathspec 'fix/update-deps' did not match any file(s) known to git
```

**To Reproduce**
1. Run `wash new actor --git https://github.com/wasmcloud/project-templates --subfolder actor/hello --branch fix/update-deps  `

### PR DESCRIPTION
**Pull request by brooksmtownsend**
Signed-off-by: Brooks Townsend <brooksmtownsend@gmail.com>

## Feature or Problem
This PR addresses an issue where our shallow clone of a repository wouldn't `fetch` the branches. Now the `wash new` command will fetch a git repository using only the supplied branch, defaulting to `main` if not supplied.

## Related Issues
Fixes #845

## Release Information
next

## Consumer Impact
This doesn't change default behavior, but users that are attempting to clone templates from a repo where the primary branch is `master` will have to supply `--branch master`

### Manual Verification
Made sure this worked with #1184

### CODE REVIEW

File: crates/wash-lib/src/generate/git.rs [hunk 1]
```diff
@@ -41,7 +41,16 @@ pub async fn clone_git_template(opts: CloneTemplate) -> Result<()> {
...
     let cmd_out = Command::new("git")
-        .args(["clone", &repo_url, "--depth", "1", "--no-checkout", "."])
+        .args([
+            "clone",
+            &repo_url,
+            "--depth",
+            "1",
+            "--no-checkout",
+            "--branch",
+            &opts.repo_branch,
```
Comment (brooksmtownsend) [inline crates/wash-lib/src/generate/git.rs:51]: Note that, if not specified, this will be `"main"`

Comment (vados-cosmonic) [reply crates/wash-lib/src/generate/git.rs:51]: Thanks for noting this -- I see where the default gets set in `prepare_local_template` and it is weird to not be building this a bit more dynamically but we can cross that bridge when we get there

**Review by vados-cosmonic — APPROVED** [review]
LGTM :rocket:
