### PR TITLE
Fix(wash)=disallow overriding hostcore labels

### LINKED ISSUE #4234: [BUG] hostcore.* labels can be overridden
### Affected project(s)

- [ ] documentation
- [ ] examples
- [x] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

The three "hostcore.*" labels, arch, os and osfamily should not be overridable. Today, that is possible:

Image

### Steps to reproduce

1. Run `wash up --label hostcore.os=foo`
2. Run `wash get inventory`
3. See overridden label

### Expected behavior

We should ensure that the hostcore labels are always set based on the host platform, not what's supplied.

### Environment

- OS: [e.g. Linux, MacOS]
- Shell [e.g. bash, zsh, powershell]
- wasmcloud Version [e.g. 0.81.0]

### Screenshots / Logs / Additional context

_No response_

### PR DESCRIPTION
**Pull request by vados-cosmonic**
## Feature or Problem

Resolves #4234

### CODE REVIEW

**Review by ricochet — APPROVED** [review]

File: crates/wash/tests/wash_label.rs [hunk 1]
```diff
@@ -37,3 +37,31 @@ async fn integration_label_host_serial() -> Result<()> {
...
+    let wash_instance = TestWashInstance::create().await?;
+
+    let output = Command::new(env!("CARGO_BIN_EXE_wash"))
+        .args([
+            "label",
+            &wash_instance.host_id,
+            "hostcore.example=test",
+            "--output",
+            "json",
+            "--ctl-port",
```
Comment (thomastaylor312) [inline crates/wash/tests/wash_label.rs:53]: Nit: Can you switch this whole block to use the `wash_instance.wash_cmd()` (or something like that, can't remember the function name I added) that takes care of setting all of the ctl port and other stuff?

**Review by thomastaylor312 — APPROVED** [review]

File: crates/wash/tests/wash_label.rs (hunk 1 above)
Comment (vados-cosmonic) [reply crates/wash/tests/wash_label.rs:53]: Sure, will use that!
