### PR TITLE
fix(lattice-client-react): refresh washboard content when URL change

### LINKED ISSUE #3551: [BUG-Washboard] wont update the washboard content when changing url
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [X] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

Changing the URL should be able to fetch the information about the information of the lattice.
Even if the connection is established the washboard does not change.
 

### Steps to reproduce

Start a wasmCloud host with a websocket port, not the default 4223.

E.g.: 
```bash
wash up --nats-websocket-port 4224
```

Go to another terminal and start the washboard

```bash
wash ui
```

visit http://localhost:3030/

go to the settings and change the lattice url to `ws://localhost:4224`

### Expected behavior

The washboard should have the newly started host, but it is empty.

The expected behaviour is to fetch the host (or lattice) inventory, links and configs and display on the board.

### Environment

- OS: MacOS
- zsh
wash          v0.36.1
├ nats-server v2.10.20
├ wadm        v0.18.0
└ wasmcloud   v1.4.0

### Screenshots / Logs / Additional context

You can validate with tools or with the browsers developer tools if the websocket communication is functioning or not.

In the screenshot `malna` is where the host is, based on the reproduction steps it will be `localhost` 

image

image

image

### PR DESCRIPTION
**Pull request by Ruby-rc**
## Feature or Problem
Fix washboard wnot change when webssocket url change

- Add LatticeConfigProvider component to manage lattice configuration
- Update AppLatticeClientProvider to use LatticeConfigProvider
- Modify ConnectionStatus and LatticeSettings to use new config context
- Update useLatticeConfig hook to use LatticeConfigContext

## Related Issues
closes #3551

https://github.com/user-attachments/assets/ba75ad38-bc06-4e05-9139-c8cab5438520

### CODE REVIEW

File: typescript/apps/washboard-ui/src/app/components/lattice-settings.tsx [hunk 1]
```diff
@@ -30,7 +30,14 @@ type LatticeFormInput = z.input<typeof formSchema>;
...
 
 export function LatticeSettings(): ReactElement {
-  const [{latticeUrl, latticeId, ctlTopicPrefix, retryCount}, setConfig] = useLatticeConfig();
+  const {config, setConfig} = useLatticeConfig();
+
+  const {latticeUrl, latticeId, ctlTopicPrefix, retryCount} = config ?? {
+    latticeUrl: '',
+    latticeId: 'default',
+    ctlTopicPrefix: 'wasmcloud.control',
+    retryCount: 5,
```
Comment (markkovari) [inline typescript/apps/washboard-ui/src/app/components/lattice-settings.tsx:39]: Quick question: is there any particular reason why this is not `10` as [here](https://github.com/wasmCloud/wasmCloud/blob/9622399aeff74d2a79c3bed5980780fc57d98967/typescript/packages/lattice-client-core/src/lattice-client.ts#L43)?

File: typescript/apps/washboard-ui/src/app/components/app-lattice-client-provider.tsx [hunk 2]
```diff
@@ -1,20 +1,38 @@
...
+  const config: LatticeClientOptions = {
+    config: {
+      latticeUrl: import.meta.env.VITE_NATS_WEBSOCKET_URL ?? 'ws://localhost:4223',
+      ...parameters,
+    },
+    getNewConnection: (c) =>
+      new NatsWsLatticeConnection({
+        latticeUrl: c.latticeUrl,
+      }),
+  };
```
Comment (markkovari) [inline typescript/apps/washboard-ui/src/app/components/app-lattice-client-provider.tsx:21]:
```suggestion
    getNewConnection: ({latticeUrl}) =>
      new NatsWsLatticeConnection({
        latticeUrl,
      }),
  };
```

this might be omitted here, if you want.

File: typescript/packages/lattice-client-react/src/context/lattice-config-provider.tsx [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+
+type SetConfigFunction = (value: LatticeClientConfigInput) => void;
+
+export type LatticeConfigContextType = {
+  config: LatticeClientConfigOutput;
+  setConfig: SetConfigFunction;
+};
+
+export const LatticeConfigContext = React.createContext<LatticeConfigContextType>({
+  config: {} as LatticeClientConfigOutput,
```
Comment (markkovari) [inline typescript/packages/lattice-client-react/src/context/lattice-config-provider.tsx:16]: As far as I remember this warning will break some CI runs. Would you mind to move the Context into a different file for the HMR? Like [this](https://github.com/wasmCloud/wasmCloud/commit/314d895548107011734b2b6c936f021f255b3b66)?

**Review by markkovari — COMMENTED** [review]
🚀 Omg, I love this. I spent a few hours trying to debug why one of the useCallbacks are not triggered on value change, but with no success. Looking good, just have a few questions, since I went through this code too.

File: typescript/apps/washboard-ui/src/app/components/app-lattice-client-provider.tsx (hunk 2 above)
Comment (Ruby-rc) [reply typescript/apps/washboard-ui/src/app/components/app-lattice-client-provider.tsx:21]: Good suggestion! I will use it.

File: typescript/apps/washboard-ui/src/app/components/lattice-settings.tsx (hunk 1 above)
Comment (Ruby-rc) [reply typescript/apps/washboard-ui/src/app/components/lattice-settings.tsx]: There is no need for the default value, I remove it.

File: typescript/packages/lattice-client-react/src/context/lattice-config-provider.tsx (hunk 3 above)
Comment (Ruby-rc) [reply typescript/packages/lattice-client-react/src/context/lattice-config-provider.tsx]: Okay, fix it.

and I'm not sure if you prefer one commit or separate ones, so I've submitted each change separately for now.

File: typescript/apps/washboard-ui/src/app/components/app-lattice-client-provider.tsx (hunk 2 above)
Comment (lachieh) [reply typescript/apps/washboard-ui/src/app/components/app-lattice-client-provider.tsx]: we can go _even shorter_

```suggestion
getNewConnection: ({latticeUrl}) => new NatsWsLatticeConnection({ latticeUrl }),
```

**Review by lachieh — APPROVED** [review]
Looks good! Thanks for the change @Ruby-rc!

And thanks @markkovari for the investigation and review comments. Super helpful.

Small suggestion, completely optional. I'll merge when you're ready @Ruby-rc!

**Review by brooksmtownsend — APPROVED** [review]
Thank you @Ruby-rc !
