### PR TITLE
fix(host): start provider from file by CLI

### LINKED ISSUE #4645: [BUG] Timed out waiting for applicable event, operation may have failed
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [x] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

Hi, there. I ran wasmCloud host.

Logs:

```
wash up
>>> ⡀⠀  Downloading NATS ...                                                                                                                                                   👀 Found nats-server version on the disk: nats-server: v2.10.20
✅ Using nats-server version [v2.10.20]
>>> ⢃⠀  Starting NATS ...                                                                                                                                                      ℹ️  NATS server successfully started, using config @ [/home/pagafonov/.wash/downloads/nats.conf]
ℹ️  NATS server logs written to [/home/pagafonov/.wash/downloads/nats.log]
>>> ⢋⠀  Starting wadm ...                                                                                                                                                      ℹ️  Found a new patch version of wadm: 0.20.3
👀 Found wadm version on the disk: wadm 0.20.2
🎣 Downloading new wadm from https://github.com/wasmcloud/wadm/releases/download/v0.20.3/wadm-v0.20.3-linux-amd64.tar.gz
>>> ⠉⠙  Starting wadm ...                                                                                                                                                      🎯 Saved wadm to /home/pagafonov/.wash/downloads/wadm
🏃 Running in interactive mode.
🎛️ To start the dashboard, run `wash ui`
🚪 Press `CTRL+c` at any time to exit
2025-07-14T07:45:55.934698Z  INFO async_nats: event: connected
2025-07-14T07:45:55.934892Z  INFO async_nats: event: connected
2025-07-14T07:45:55.954201Z  INFO wasmcloud_host::wasmbus::jetstream: bucket already exists. Skipping creation. bucket=LATTICEDATA_default
2025-07-14T07:45:55.954611Z  INFO wasmcloud_host::wasmbus::jetstream: bucket already exists. Skipping creation. bucket=CONFIGDATA_default
2025-07-14T07:45:55.958082Z  INFO wasmcloud_host::wasmbus: wasmCloud host started host_id="NCMB3ZJQOE2477FFLZZG3AWUWVNN6VDLE72X52ADP4EXIRWGQEYDBXR6"
```

Then I start the provider through CLI.

```
wash start provider ./bin_ollama_provider.par.gz ollama_id --host-id NCMB3ZJQOE2477FFLZZG3AWUWVNN6VDLE72X52ADP4EXIRWGQEYDBXR6 --config cfg1
```

The provider has started successfully:

```
2025-07-14T07:46:10.152956Z  INFO wasmcloud_host::wasmbus::ctl: handling start provider provider_ref="file:///home/pagafonov/projects/kuber-boring/components/ollama_provider/build/bin_ollama_provider.par.gz" provider_id="VBBNE5FV3R226LSVISXQOSLKM5K77OQ5TRBMKRR2WBIA2ZJDZ7GPKFSF"
2025-07-14T07:46:10.589163Z  INFO wasmcloud_host::wasmbus: provider started provider_ref="/home/pagafonov/projects/kuber-boring/components/ollama_provider/build/bin_ollama_provider.par.gz" provider_id="ollama_id"
time=2025-07-14T10:46:10.598+03:00 level=INFO msg="MemoryMonitor started" limit=17179869184 interval=2s
time=2025-07-14T10:46:10.598+03:00 level=INFO msg="provider started" id=ollama_id
time=2025-07-14T10:46:10.599+03:00 level=INFO source=routes.go:1235 msg="server config" env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_CONTEXT_LENGTH:4096 OLLAMA_DEBUG:INFO OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://0.0.0.0:11432 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:2562047h47m16.854775807s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:~/.ollama/models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NEW_ENGINE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://* vscode-file://*] OLLAMA_SCHED_SPREAD:false ROCR_VISIBLE_DEVICES: http_proxy: https_proxy: no_proxy:]"
time=2025-07-14T10:46:10.600+03:00 level=INFO source=images.go:476 msg="total blobs: 35"
time=2025-07-14T10:46:10.600+03:00 level=INFO source=images.go:483 msg="total unused blobs removed: 0"
time=2025-07-14T10:46:10.600+03:00 level=INFO source=routes.go:1288 msg="Listening on [::]:11432 (version 0.0.0)"
time=2025-07-14T10:46:10.600+03:00 level=INFO source=gpu.go:217 msg="looking for compatible GPUs"
time=2025-07-14T10:46:10.606+03:00 level=INFO source=gpu.go:377 msg="no compatible GPUs were discovered"
time=2025-07-14T10:46:10.607+03:00 level=INFO source=types.go:130 msg="inference compute" id=0 library=cpu variant="" compute="" driver=0.0 name="" total="31.1 GiB" available="18.7 GiB"
time=2025-07-14T10:46:15.590+03:00 level=INFO msg="Handling health check"
```

And I got the error from start provider command:

```
Failed starting provider file:///home/pagafonov/projects/kuber-boring/components/ollama_provider/build/bin_ollama_provider.par.gz on host NCMB3ZJQOE2477FFLZZG3AWUWVNN6VDLE72X52ADP4EXIRWGQEYDBXR6

Caused by:
    Timed out waiting for applicable event, operation may have failed
```

### Steps to reproduce

It might be a problem with my provider, but here's what I do:

1. Run `wash up`
2. Build provider
3. Run provider `wash start provider <provider file> provider-id --host-id <host_id>`

### Expected behavior

Output: Provider [ollama_provider] (ref: [ollama_id]) started on host [NCMB3ZJQOE2477FFLZZG3AWUWVNN6VDLE72X52ADP4EXIRWGQEYDBXR6]

### Environment

- OS: Ubuntu 24.04.1 LTS
- Shell: bash
- wash          v0.40.0
├ nats-server v2.10.20
├ wadm        v0.20.2
└ wasmcloud   v1.6.1

### Screenshots / Logs / Additional context

_No response_

### PR DESCRIPTION
**Pull request by if0ne**
## Feature or Problem
Incorrect `provider_ref` was sent to `provider_started` event if it was a file.

## Related Issues
Closes #4645 

## Consumer Impact
None

### Unit Test(s)
`parse_references` was modified in `crates/host/src/lib.rs:212`

### Manual Verification

Now it works successfully
```
wash start provider ./bin_ollama_provider.par.gz my-id --host-id NC645VOKJPRD23O7LZH5RFTWP3TRWAXVHY5TUJZW3MXKX5OEJEMKRCL4

Provider [my-id] (ref: [file:///home/pagafonov/projects/kuber-boring/components/ollama_provider/build/bin_ollama_provider.par.gz]) started on host [NC645VOKJPRD23O7LZH5RFTWP3TRWAXVHY5TUJZW3MXKX5OEJEMKRCL4]
```

### CODE REVIEW

File: crates/host/src/lib.rs [hunk 1]
```diff
@@ -70,7 +70,7 @@ impl AsRef<str> for ResourceRef<'_> {
         match self {
             // Resource ref must have originated from a URL, which can only be constructed from a
             // valid string
-            ResourceRef::File(path) => path.to_str().expect("invalid file reference URL"),
+            ResourceRef::File(url, _) => url,
```
Comment (thomastaylor312) [inline crates/host/src/lib.rs]: I think we can get away without needing to add an extra field. Because we have parsed this from a URL, we can always just add back on the `file://` to the string value returned back here when we use it. To solve the bug, when the event is sent, you can match on the enum type and preface if needed. The other option is to parse and trim the `file://` prefix on the wash side!

**Review by thomastaylor312 — CHANGES_REQUESTED** [review]
Thanks for finding the bug and submitting the fix! I'd prefer not to duplicate the data here and break a `pub` enum if we don't have to

File: crates/host/src/lib.rs (hunk 1 above)
Comment (if0ne) [reply crates/host/src/lib.rs]: I decided to just strip where the check happens. I didn't look at the whole path of using `provider_ref` after calling `resolve_ref`. 

https://github.com/wasmCloud/wasmCloud/blob/669d3bda4dd618aa750d9fb2f5772aa6a80a20d5/crates/wash/src/lib/cli/start.rs#L248

Maybe `resolve_ref` is not needed in this case.

**Review by brooksmtownsend — APPROVED** [review]
Nice work @if0ne ! Looks like you'll need to sign off your commits, the details on the failing check will show you the command to run https://github.com/wasmCloud/wasmCloud/pull/4646/checks?check_run_id=46453523400

**Comment by brooksmtownsend** [comment]
Merging when ready! 🫡

**Comment by brooksmtownsend** [comment]
Ugh @if0ne looks like this needs a rebase with the base branch thanks to some changes coming in with dependencies. Would you mind rebasing off main, or I'm happy to do it too

**Comment by brooksmtownsend** [comment]
19th time is the charm 🤞🏻
